version: "3.2"

services:
  app:
    image: devregistry20250126.azurecr.io/appliancestoretestspringbootmain:v1
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    restart: always