apiVersion: apps/v1
kind: Deployment
metadata:
  name: appliances-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appliances-store
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: appliances-store
    spec:
      containers:
        - name: appliances-store
          image: devregistry20250126.azurecr.io/appliances-store:v1-73219ab
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"

