apiVersion: v1
kind: Service
metadata:
  name: rolling-update-app-service
spec:
  selector:
    app: rolling-update-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer