apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update-app
spec:
  replicas: 2  # Minimum replicas for rolling update
  selector:
    matchLabels:
      app: rolling-update-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Allow only 1 pod to be unavailable during update
      maxSurge: 1        # Add 1 extra pod during the update
  template:
    metadata:
      labels:
        app: rolling-update-app
    spec:
      containers:
        - name: rolling-update-app
          image: devregistry20250126.azurecr.io/appliancestoretestspringbootmain_app:v1  # Initial version
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"

