INSERT INTO employee (name, email, password, department) VALUES
    ('Phobos','phobos@gmail.com','111','salle'),
    ('Phobos','phobos@gmail.com','111','salle'),
    ('Phobos','phobos@gmail.com','111','salle'),
    ('Phobos','phobos@gmail.com','111','salle'),
    ('Phobos','phobos@gmail.com','111','salle'),
    ('Phobos','phobos@gmail.com','111','salle'),
    ('Phobos','phobos@gmail.com','111','salle'),
    ('Phobos','phobos@gmail.com','111','salle'),
    ('Phobos','phobos@gmail.com','111','salle'),
    ('Phobos','phobos@gmail.com','111','salle'),
    ('Phobos','phobos@gmail.com','111','salle'),
    ('Phobos','phobos@gmail.com','111','salle'),
    ('Moon','phobos@gmail.com','222','salle'),
    ('Deimos','deimos@gmail.com','333','security'),
    ('Europa','europa@gmail.com','444','security');