create table admin
(
    id       bigint generated by default as identity,
    name     varchar(100) not null,
    email    varchar(255) not null,
    password varchar(255) not null,
    role     enum ('ADMIN','CLIENT','EMPLOYEE'),
    primary key (id)
);
create table appliance
(
    power           integer                              not null check (power >= 1),
    price           numeric(38, 2)                       not null,
    id              bigint generated by default as identity,
    manufacturer_id bigint                               not null,
    description     varchar(1000),
    characteristic  varchar(255)                         not null,
    model           varchar(255)                         not null,
    name            varchar(255)                         not null,
    category        enum ('BIG','SMALL')                 not null,
    power_type      enum ('AC110','AC220','ACCUMULATOR') not null,
    primary key (id)
);
create table cart
(
    client_id bigint unique,
    id        bigint generated by default as identity,
    primary key (id)
);
create table client
(
    enabled          boolean      not null,
    id               bigint generated by default as identity,
    name             varchar(100) not null,
    email            varchar(255) not null,
    password         varchar(255) not null,
    shipping_address varchar(255) not null,
    role             enum ('ADMIN','CLIENT','EMPLOYEE'),
    primary key (id)
);
create table employee
(
    id         bigint generated by default as identity,
    department varchar(100) not null,
    name       varchar(100) not null,
    email      varchar(255) not null,
    password   varchar(255) not null,
    role       enum ('ADMIN','CLIENT','EMPLOYEE'),
    primary key (id)
);
create table manufacturer
(
    id   bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);
create table "order"
(
    total       numeric(38, 2) not null,
    client_id   bigint,
    employee_id bigint,
    id          bigint generated by default as identity,
    status      enum ('APPROVED','CANCELLED','DELIVERED','PENDING','SHIPPED'),
    primary key (id)
);
create table order_row
(
    amount       numeric(38, 2) not null,
    appliance_id bigint         not null,
    cart_id      bigint,
    id           bigint generated by default as identity,
    number       bigint         not null check (number >= 1),
    "order_id"   bigint,
    primary key (id)
);
alter table if exists appliance
    add constraint FKhqyja0pte5uumatg7fjkes9eu foreign key (manufacturer_id) references manufacturer on delete cascade;
alter table if exists cart
    add constraint FK6ycuj5rglff1ml1pdpuw5kf82 foreign key (client_id) references client;
alter table if exists "order"
    add constraint FKhqad2xyyn10pct9vramixbm8n foreign key (client_id) references client on delete cascade;
alter table if exists "order"
    add constraint FKdjonorx78bdje2vp5oyrt0qrq foreign key (employee_id) references employee on delete cascade;
alter table if exists order_row
    add constraint FKaais25qulr920sj6n1w90keem foreign key (appliance_id) references appliance on delete cascade;
alter table if exists order_row
    add constraint FKijroa124w1vhq9lipq2mcui9t foreign key (cart_id) references cart;
alter table if exists order_row
    add constraint FKf9vefh5rgday7o476pwijq1xp foreign key ("order_id") references "order";
