image:
  repository: devregistry20250126.azurecr.io/appliances-store
  tag: -2590165
  pullPolicy: IfNotPresent
replicaCount: 2
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi
service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
