name: STORE-CICD

on:
  push:
    branches:
      - main

env:
  REGISTRY: devregistry20250126.azurecr.io  # Replace with your ACR registry name
  IMAGE_NAME: appliances-store

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for versioning

      - name: Check if secrets are set
        run: |
          echo "Checking if secrets are set"
          if [ -z "${{ secrets.AZURE_CLIENT_ID }}" ]; then echo "AZURE_CLIENT_ID is not set"; exit 1; fi
          if [ -z "${{ secrets.AZURE_TENANT_ID }}" ]; then echo "AZURE_TENANT_ID is not set"; exit 1; fi
          if [ -z "${{ secrets.AZURE_SUBSCRIPTION_ID }}" ]; then echo "AZURE_SUBSCRIPTION_ID is not set"; exit 1; fi
          echo "All secrets are set"

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry (ACR)
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Version from Git
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV


      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.version }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify Docker Image Push
        run: |
          echo "Verifying image push to ACR"
          az acr repository show-tags --name ${{ env.REGISTRY }} --repository ${{ env.IMAGE_NAME }} --output table

      - name: Logout from Azure Container Registry (ACR)
        run: |
          docker logout ${{ env.REGISTRY }}

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Helm Values.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.image.tag=env(VERSION)' src/main/resources/helm/values.yaml

      - name: Update Helm Chart Version
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version=strenv(VERSION)' src/main/resources/helm/Chart.yaml

      - name: Validate Helm Chart Updates
        run: |
          echo "Updated values.yaml:"
          cat helm/values.yaml
          echo "Updated Chart.yaml:"
          cat helm/Chart.yaml

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/values.yaml helm/Chart.yaml
          git diff-index --quiet HEAD || git commit -m "CI: Update to version $VERSION"
          git push